package dal;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;

import exceptions.DatabaseAccessException;
import model.OrderLine;
import model.SaleOrder;

public class SaleOrderDB implements SaleOrderDBIF {
	
	private static final String CREATE_STATEMENT = "INSERT INTO SaleOrder(date, deliveryStatus, deliveryDate,"
			+ " paymentDate, amount, customerPhoneno) VALUES(?, ?, ?, ?, ?, ?)";
	
	private PreparedStatement createStatement;
	
	public SaleOrderDB() throws DatabaseAccessException {
		try {
			createStatement = DbConnection.getInstance().getConnection().prepareStatement(CREATE_STATEMENT, Statement.RETURN_GENERATED_KEYS);
		} catch (SQLException e) {
			//e.printStackTrace();
			throw new DatabaseAccessException(DatabaseAccessException.CONNECTION_MESSAGE);
		}
	}

	/**
	 * Inserts an order into the database and sets the order's id to the one generated by the database
	 * @param order the order to be inserted into the database
	 * @return the order with the set id
	 * @throws DatabaseAccessException
	 */
	@Override
	public SaleOrder insertOrder(SaleOrder order) throws DatabaseAccessException {	
		try {
			createStatement.setTimestamp(1, Timestamp.valueOf(order.getDate()));
			createStatement.setString(2, order.getDeliveryStatus());
			createStatement.setTimestamp(3, Timestamp.valueOf(order.getDeliveryDate()));
			createStatement.setTimestamp(4, Timestamp.valueOf(order.getPaymentDate()));
			createStatement.setBigDecimal(5, order.getPrice());
			createStatement.setString(6, order.getCustomer().getPhoneno());
			
			order.setId(DbConnection.getInstance().executeSqlInsertWithIdentity(createStatement));
			
		} catch (SQLException e) {
			//e.printStackTrace();
			throw new DatabaseAccessException(e.getMessage());
		}
		
		return order;
	}

}
